### ISSUE TITLE
Possible logic error in settings.xml rename process at start

### ISSUE THREAD

**Issue by Wolf-Z** [scVENUS/sctime#17]
After starting sctime (from latest master (df0149c41390f20907447c9f113599fadbf1dd99) I get an error like

"settings.xml.tmp cannot be renamed to settings.xml" (as message box) while indeed settings.xml has a new timestamp afterwards.

"Permissions denied" is also shown - but all files are RW (also the Directory above with +x).

The previous  commit works instead.

Looks like this bug was introduced with the current commit df0149c41390f20907447c9f113599fadbf1dd99 . 
I also used strace to look into this issue. The rename return codes are always "0".

Thx! :)

**Comment by desperadoduck** [comment]
yes, 0 means success. I'll fix the code.

**Comment by desperadoduck** [comment]
the thing is, QFile::rename (which we use for the windows case) has the logic the other way round, so one has to be careful here. Thanks for spotting that!

**Comment by desperadoduck** [comment]
should be fixed now
